name: Build module.tar.gz and upload to registry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: main
        description: realsense module branch to run on
  pull_request:


permissions:
  id-token: write
  contents: read

jobs:
  module:
    name: Intel RealSense module.tar.gz
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
            container:
              image: ubuntu:22.04
            artifact-name: module-arm64
            profile-name: arm64-profile
            platform: linux/arm64
          - os: ubuntu-22.04
            container:
              image: ubuntu:22.04
            artifact-name: module-amd64
            profile-name: amd64-profile
            platform: linux/amd64
          - os: macos-latest
            platform: darwin/arm64
            artifact-name: module-darwin-arm64

    container: ${{ matrix.container }}

    steps:
      - name: Set checkout ref (release)
        if: github.event_name == 'release'
        run: echo "CHECKOUT_REF=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set checkout ref (dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: echo "CHECKOUT_REF=${{ inputs.ref }}" >> $GITHUB_ENV

      - name: Test var set
        run: echo $CHECKOUT_REF

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CHECKOUT_REF }}

      - name: Restore cached libraries
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ matrix.os }}-conan-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ matrix.os }}-conan-

      - name: Install dependencies
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            apt-get update && apt-get install -y make sudo
          fi
          make setup

      - name: Build
        run: |
          make module.tar.gz

      - name: Upload module artifact
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: module.tar.gz

      - name: Upload module to registry
        if: github.event_name == 'release'
        uses: viamrobotics/upload-module@main
        with:
          platform: ${{ matrix.platform }}
          version: ${{ github.ref_name }}
          key-id: ${{ secrets.viam_key_id}}
          key-value: ${{ secrets.viam_key_value }}
