name: Build module.tar.gz and upload to registry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: main
        description: realsense module branch to run on
  pull_request:


permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Intel RealSense module.tar.gz
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
            artifact-name: module-arm64
            platform: linux/arm64
          - os: ubuntu-22.04
            artifact-name: module-amd64
            platform: linux/amd64
          - os: macos-latest
            platform: darwin/arm64
            artifact-name: module-darwin-arm64
    steps:
      - name: Set checkout ref (release)
        if: github.event_name == 'release'
        run: echo "CHECKOUT_REF=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set checkout ref (dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: echo "CHECKOUT_REF=${{ inputs.ref }}" >> $GITHUB_ENV

      - name: Test var set
        run: echo $CHECKOUT_REF

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CHECKOUT_REF }}

      - name: Restore cached libraries
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ matrix.os }}-conan-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ matrix.os }}-conan-

      - name: Install dependencies
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y make
          fi
          make setup

      - name: Build
        run: |
          make module.tar.gz

      - name: Upload module artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: module.tar.gz
          retention-days: 7

  upload:
    name: Upload modules to registry
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - artifact-name: module-arm64
            platform: linux/arm64
            artifact-path: ./artifacts/linux-arm64/
          - artifact-name: module-amd64
            platform: linux/amd64
            artifact-path: ./artifacts/linux-amd64/
          - artifact-name: module-darwin-arm64
            platform: darwin/arm64
            artifact-path: ./artifacts/darwin-arm64/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download module artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}

      - name: Upload module to registry
        uses: viamrobotics/upload-module@main
        with:
          meta-path: meta.json
          module-path: ${{ matrix.artifact-path }}/module.tar.gz
          platform: ${{ matrix.platform }}
          version: ${{ github.ref_name }}
          key-id: ${{ secrets.viam_key_id}}
          key-value: ${{ secrets.viam_key_value }}
